# Generated by Django 4.2.23 on 2025-07-28 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_about_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='featured_image',
            new_name='profile_image',
        ),
    ]
